In [1]:
import pickle

In [2]:
import pandas as pd

In [3]:
output_dir_name = "gemini-2.5-flash"

In [4]:
with open(f"{output_dir_name}/titles_with_tags_dict_processed.pkl", "rb") as f:
    titles_with_tags_dict_processed = pickle.load(f)

In [5]:
data = []

In [6]:
for title, tags in titles_with_tags_dict_processed.items():
    for tag in tags:
        data.append((title, tag))

In [7]:
df = pd.DataFrame(data=data, columns=["title", "tag"])

In [8]:
dfgr = df.groupby(by=["tag"]).agg({"title": "nunique"}).reset_index()
dfgr.columns = ["tag", "count"]
dfgr = dfgr.sort_values(by=["count"], ascending=False).reset_index(drop=True)
dfgr.head(32)

                            tag  count
0                    humanities    250
1                     education    226
2                 digital_media    210
3               russian_studies    199
4                       culture    143
5                     sociology    118
6                      politics    102
7                  data_science     98
8                     marketing     98
9                     economics     97
10                  linguistics     96
11         software_development     85
12      business_and_management     85
13                asian_studies     73
14                          law     73
15           economic_geography     68
16                   psychology     65
17           project_management     55
18             event_management     52
19                      finance     46
20             film_and_theater     41
21      artificial_intelligence     38
22                         arts     38
23  natural_language_processing     37
24              web_development     27
25             machine_learning     27
26             public_relations     26
27            content_marketing     23
28                       africa     22
29                 student_life     21
30                urban_studies     20
31           mobile_development     19

In [9]:
df[df["tag"] == "humanities"].head()

                                                title         tag
6   Антрополе - научно-популярный видео-подкаст о ...  humanities
13  Разработка, создание и ведение сайта, посвящен...  humanities
17  Перевод с английского языка коллективной моног...  humanities
30  Привязанность к месту и психосоциальное здоров...  humanities
78   Исторические сферы влияния: создание базы данных  humanities

In [10]:
df[df["title"] == "Исторические сферы влияния: создание базы данных"]

                                               title                 tag
76  Исторические сферы влияния: создание базы данных        data_science
77  Исторические сферы влияния: создание базы данных  economic_geography
78  Исторические сферы влияния: создание базы данных          humanities